In [1]:
from lib.pywordle import *
import numpy as np
from tqdm.notebook import tqdm, trange
import time    # to be used in loop iterations

In [1]:
with open('words.txt') as f:
    words = f.read().splitlines()
    f.close()

In [3]:
with open('words.txt', 'w') as f:
    for word in words:
        f.write(word.lower() + "\n")
    f.close()

In [2]:
print(len(words))

2315


In [5]:
wordle = WordleSolver()

In [6]:
wordle.reset()
wordle.setTarget(words.index("acute"))
print(wordle.makeGuess(words.index("vivid")))

1328


In [7]:
wordle.reset()
wordle.setTarget(words.index("aback"))
print(wordle.makeGuess(words.index("fuzzy")))

1352


In [8]:
def compute_next_guess(target, guesses):
    wordle = WordleSolver()
    wordle.setTarget(target)
    for guess in guesses:
        wordle.makeGuess(int(guess))
    valids = np.array(wordle.remainingWordList())
    results = np.zeros(len(words))
    for i in valids:
        if (len(valids) > 1 & target == i): 
            continue
        wordle.reset()
        for guess in guesses:
            wordle.makeGuess(int(guess))
        results[i] = wordle.makeGuess(int(i))
    return results[0:-1]
   

In [9]:
wordle = WordleSolver()
wordle.setTarget(words.index('wight'))
guesses = "chuck, hobby, aphid, fifth, eight, light, might, night, right, sight, tight, wight".split(", ")
print(wordle.makeGuess(words.index("chuck")))
print(wordle.makeGuess(words.index("hobby")))
print(wordle.makeGuess(words.index("aphid")))
print(wordle.makeGuess(words.index("fifth")))
print(wordle.makeGuess(words.index("eight")))
print(wordle.makeGuess(words.index("light")))
print(wordle.makeGuess(words.index("might")))
print(wordle.makeGuess(words.index("night")))
print(wordle.makeGuess(words.index("right")))
print(wordle.makeGuess(words.index("sight")))
print(wordle.makeGuess(words.index("tight")))
print(wordle.makeGuess(words.index("wight")))

128
51
21
10
7
6
5
4
3
2
1
1


In [10]:
wordle = WordleSolver()
#second2 = np.array(wordle.generateTargetTable(words.index("sight"), 0, len(words)))

In [ ]:
second3 = np.array(generateTargetTable(words.index("sight"), 8))

In [ ]:
second = np.load("sight.np.npy")

In [ ]:
print(second)
#print(second2)
print(second3)

[[  0 107 124 ... 288  49 280]
 [107   0  47 ... 125  42  48]
 [124  47   0 ... 107  59  51]
 ...
 [288 125 107 ...   0  39 101]
 [ 49  42  59 ...  39   0  21]
 [280  48  51 ... 101  21   0]]
[[925 107 124 ... 288  49 280]
 [107  30  12 ...  20  10  30]
 [124  12  12 ...   8  10  12]
 ...
 [  1   1   1 ...   1   1   1]
 [  1   1   1 ...   1   1   1]
 [  1   1   1 ...   1   1   1]]


In [ ]:
for i in range(len(words)):
    if (second[i,0] == 280):
        print(second[i])


[280  55  49 ... 110  23 297]
[280 108 111 ... 267  48 161]
[280  48  51 ... 101  21   0]


In [ ]:
for i in range(2312):
    if (second3[i,0] == 280):
        print(second3[i])

In [ ]:
second

array([[  0, 107, 124, ..., 288,  49, 280],
       [107,   0,  47, ..., 125,  42,  48],
       [124,  47,   0, ..., 107,  59,  51],
       ...,
       [288, 125, 107, ...,   0,  39, 101],
       [ 49,  42,  59, ...,  39,   0,  21],
       [280,  48,  51, ..., 101,  21,   0]])

In [ ]:
guess1 = np.argmax(second) // np.shape(second)[0]
guess2 = np.argmax(second) % np.shape(second)[1]
print("target = ", words[guess1])
print("guess = ", words[guess2])

target =  fuzzy
guess =  mummy


In [ ]:
guess1 = np.argmax(second2) // np.shape(second2)[0]
guess2 = np.argmax(second2) % np.shape(second2)[1]
print("target = ", words[guess1])
print("guess = ", words[guess2])

NameError: name 'second2' is not defined

In [ ]:
print(second2[guess1, guess2])

1352
